### ISSUE TITLE
Use GTK+ look and feel (rather than Metal) on Linux

### ISSUE THREAD

**Issue by hartwork** [psal/JStylo-Anonymouth#5]
JSANGUIChooser.java reads:

```
                try {
                    UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                } catch (Exception e) {
                    System.err.println("Look-and-Feel error! (Not on Windows)");
                }
```

This is definitely missing support for the GTK+ look and feel -- Metal hurts my eyes :-)

This relates to branch anonymouth_master.

**Comment by psal** [comment]
Dear user,

JStylo-Anonymouth is no longer maintained. Instead, two separate projects are opened for JStylo and Anonymouth.
The Anonymouth repository is still in development and will be available soon.
The JStylo repository is available here:
https://github.com/psal/jstylo

Thanks,
The psal/JSAN team
